FROM debian

LABEL org.opencontainers.image.source https://github.com/hulks/meta-nao

RUN apt-get update && apt-get install --no-install-recommends --yes \
  ca-certificates \
  curl \
  file \
  python3 \
  xz-utils \
  zstd \
  && rm --recursive --force /var/lib/apt/lists/*

ARG version

COPY --chmod=744 sdk/HULKs-OS-*.sh /opt/

RUN /opt/HULKs-OS-$(uname -m)-toolchain-${version}.sh -d /naosdk -y && rm /opt/HULKs-OS-*.sh
RUN echo . /naosdk/environment-setup-corei7-64-aldebaran-linux >> /root/.bashrc
