#!/usr/bin/env bash

CURRENT_DATE=$(date +%Y-%m-%dT%H:%M:%S.%3N%:z)
INTERNAL_LOG_PATH=/home/nao/hulk/logs/${CURRENT_DATE}
EXTERNAL_LOG_PATH=$(grep -m1 '^/dev/sda1' /proc/mounts | cut -d ' ' -f 2)/logs

mkdir -p ${INTERNAL_LOG_PATH}
mkdir -p ${EXTERNAL_LOG_PATH}

ln -sf ${INTERNAL_LOG_PATH}/hulk.out ${INTERNAL_LOG_PATH}/../hulk.out
ln -sf ${INTERNAL_LOG_PATH}/hulk.err ${INTERNAL_LOG_PATH}/../hulk.err

exec /home/nao/hulk/bin/hulk --log-path ${INTERNAL_LOG_PATH} \
         > >(tee ${EXTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.out > ${INTERNAL_LOG_PATH}/hulk.out) \
        2> >(tee ${EXTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.err > ${INTERNAL_LOG_PATH}/hulk.err)
