#!/bin/sh

set -e

HEAD_ID="$(/opt/aldebaran/bin/head_id)"
QUERY_STRING="to_entries | map(select(.value.head_id == \"${HEAD_ID}\")) | .[0].key"
NAO_NUMBER="$(jq -r "${QUERY_STRING}" /media/internal/hardware_ids.json)"

if [ -z "${NAO_NUMBER}" ]; then
  exit
fi

HOSTNAME="tuhhnao${NAO_NUMBER}"

echo "[Match]
Name=wlan*

[Network]
Address=10.0.24.${NAO_NUMBER}/16

[Route]
Gateway=0.0.0.0
" > /etc/systemd/network/80-wlan.network

echo "[Match]
Name=en* eth*

[Network]
Address=10.1.24.${NAO_NUMBER}/16

[Route]
Gateway=10.1.24.1
Destination=10.2.24.0/24
" > /etc/systemd/network/80-wired.network

hostnamectl set-hostname ${HOSTNAME}
