header:
  version: 14

machine: nao-v6
distro: nao-core-minimal
target: nao-image

local_conf_header:
  meta-nao: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES ?= "package_ipk"
    EXTRA_IMAGE_FEATURES += "allow-empty-password"
    CLANGSDK = "1"

repos:
  meta-nao:
    layers:
      meta:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    commit: ae6cebca5bac9521230c69fed23b375d0de7f5f6
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
    patches:
      0003-specify-custom-dynamic-linker:
        repo: "meta-nao"
        path: "patches/0003-bindgen-clang-sysroot.patch"
      0004-compress-sdk-with-zstd:
        repo: "meta-nao"
        path: "patches/0004-compress-sdk-with-zstd.patch"
  meta-congatec-x86:
    url: "https://git.congatec.com/x86/meta-congatec-x86.git"
    commit: 1867244888ed0a5ad85f5b4ab789e1d0201deb02
    patches:
      0001-congatec-scarthgap-support:
        repo: "meta-nao"
        path: "patches/0001-congatec-scarthgap-support.patch"
      0002-congatec-new-override-syntax:
        repo: "meta-nao"
        path: "patches/0002-congatec-new-override-syntax.patch"
  meta-clang:
    url: "https://github.com/kraj/meta-clang.git"
    commit: e7dceb1c92caf7f21ef1d7b49c85328c30cffd90
  meta-intel:
    url: "https://git.yoctoproject.org/git/meta-intel"
    commit: c8cd0317ec19332bce86697f3413a82b9828b329
  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    commit: 4a7bb77f7ebe0ac8be5bab5103d8bd993e17e18d
    layers:
      meta-oe:
      meta-multimedia:
      meta-networking:
      meta-python:
