FROM ghcr.io/siemens/kas/kas:latest

LABEL org.opencontainers.image.source https://github.com/HULKs/meta-nao

COPY aldebaran_binaries.tar.gz /

RUN sudo apt-get update && sudo apt-get install --no-install-recommends --yes \
  buildah \
  qemu-user-static
